name: golang-pipeline

on:
  push:
    branches: [ "feature/new" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go modules
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      name: Update dependencies
        run: go mod tidy
        
      - name: Run Unit Tests
        run: go test ./...  # Упрощенная команда

      - name: Vet
        run: go vet .//