name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]  # Например v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Workflow triggered!"